/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/success': typeof SuccessRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/success': typeof SuccessRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/success': typeof SuccessRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/success'
    | '/u/$username'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/success'
    | '/u/$username'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/success'
    | '/u/$username'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  SuccessRoute: typeof SuccessRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  SuccessRoute: SuccessRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
